php-coveralls/php-coveralls

composer.json, phpunit.xml.dist, tests/bootstrap.php, travis.phpunit.xml
As explain in the title, this PR does three things:
* Remove the `minimum-stability` flag as `stable` is the default one.
* Upgrade all constraints to ones following Semver and so, should not break BC
* Upgrade tha autoloading to PSR-4
I need this PR meanwhile we find the issues in #75 (One of my travis-ci build can't be resolved. See [here](https://travis-ci.org/egeloen/IvoryCKEditorBundle/jobs/40826801)).
=> [Composer] Update to PSR-4 + Use Semver constraint + Remove minimum-stability

src/Satooshi/Bundle/CoverallsV1Bundle/Collector/GitInfoCollector.php
Travis runs in a detached head state which will cause the branch in coveralls to look like `(detached abf2510a)`. To fix this we look for the existence of the `TRAVIS_BRANCH` environment variable and return that if it exists.
=> Fix git branch for travis ci

src/Satooshi/Bundle/CoverallsV1Bundle/Collector/GitInfoCollector.php
Reverts satooshi/php-coveralls#102
Build is failing
https://travis-ci.org/satooshi/php-coveralls/builds/94674189
=> Revert "Fix git branch for travis ci"

README.md
Changed the `phpcov` source to `phpunit/phpcov` now published on Packagist.
Since this is version 2.x, I also fixed the command line example.
Also fixed a few typos in the README.
=> phpcov (2.x) is now available on Packagist

.travis.yml, circle.yml, composer.json, src/Satooshi/Bundle/CoverallsV1Bundle/Api/CoverallsApi.php, src/Satooshi/Bundle/CoverallsV1Bundle/Api/Jobs.php, src/Satooshi/Bundle/CoverallsV1Bundle/Command/CoverallsV1JobsCommand.php, src/Satooshi/Bundle/CoverallsV1Bundle/Repository/JobsRepository.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Api/JobsTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Repository/JobsRepositoryTest.php
Brings Coveralls more in line with modern code bases that are using
PSR-7 and newer versions of Guzzle.
Also changes the minimum PHP version to 5.5 and upgrades packages.
Fixes #80
Refs #152
**Note:** I have not tested this beyond what the continuous integration tests do. I assume they are complete enough to cover the changes made.
=> Upgrade to PHP 5.5 and Guzzle 6

.travis.yml, circle.yml, devtools/composer.json, phpunit.xml.dist, tests/Satooshi/Bundle/CoverallsV1Bundle/Api/JobsTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Collector/GitInfoCollectorTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Repository/JobsRepositoryTest.php, tests/Satooshi/Component/Log/ConsoleLoggerTest.php, tests/Satooshi/Component/System/Git/GitCommandTest.php, tests/bootstrap.php
Thank you for #204 .
This time it will be PR added only for PHP 7.1 to the support version of TravisCI.
Just as I was testing, I needed to specify test cases and php-cs-fixer version.
I corrected it carefully, so thank you for your review.
=> Add PHP7.1 for TravisCI

src/Satooshi/Bundle/CoverallsV1Bundle/Api/CoverallsApi.php, src/Satooshi/Bundle/CoverallsV1Bundle/Api/Jobs.php, src/Satooshi/Bundle/CoverallsV1Bundle/Collector/CiEnvVarsCollector.php, src/Satooshi/Bundle/CoverallsV1Bundle/Collector/CloverXmlCoverageCollector.php, src/Satooshi/Bundle/CoverallsV1Bundle/Collector/GitInfoCollector.php, src/Satooshi/Bundle/CoverallsV1Bundle/Command/CoverallsV1JobsCommand.php, src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configuration.php, src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configurator.php, src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Exception/RequirementsNotSatisfiedException.php, src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Git/Commit.php, src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Git/Remote.php, src/Satooshi/Bundle/CoverallsV1Bundle/Entity/JsonFile.php, src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Metrics.php, src/Satooshi/Bundle/CoverallsV1Bundle/Entity/SourceFile.php, src/Satooshi/Bundle/CoverallsV1Bundle/Repository/JobsRepository.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Api/JobsTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Collector/GitInfoCollectorTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Command/CoverallsV1JobsCommandTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/ConfiguratorTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Entity/Git/CommitTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Entity/Git/GitTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Entity/Git/RemoteTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Repository/JobsRepositoryTest.php, tests/Satooshi/Component/Log/ConsoleLoggerTest.php, tests/Satooshi/Component/System/Git/GitCommandTest.php, tests/Satooshi/ProjectTestCase.php
=> Code grooming

.travis.yml
so if one decides that he needs to create phar locally on his dev (eg 7.1), file will still be valid
=> phar building - set up platform.php for composer before building phar file

phpunit.xml.dist, tests/Bundle/CoverallsBundle/Api/JobsTest.php, tests/Bundle/CoverallsBundle/Collector/CiEnvVarsCollectorTest.php, tests/Bundle/CoverallsBundle/Collector/CloverXmlCoverageCollectorTest.php, tests/Bundle/CoverallsBundle/Collector/GitInfoCollectorTest.php, tests/Bundle/CoverallsBundle/Command/CoverallsJobsCommandTest.php, tests/Bundle/CoverallsBundle/Config/ConfigurationTest.php, tests/Bundle/CoverallsBundle/Config/ConfiguratorTest.php, tests/Bundle/CoverallsBundle/Console/ApplicationTest.php, tests/Bundle/CoverallsBundle/Entity/Git/CommitTest.php, tests/Bundle/CoverallsBundle/Entity/Git/GitTest.php, tests/Bundle/CoverallsBundle/Entity/Git/RemoteTest.php, tests/Bundle/CoverallsBundle/Entity/JsonFileTest.php, tests/Bundle/CoverallsBundle/Entity/MetricsTest.php, tests/Bundle/CoverallsBundle/Entity/SourceFileTest.php, tests/Bundle/CoverallsBundle/Repository/JobsRepositoryTest.php, tests/Component/File/PathTest.php, tests/Component/Log/ConsoleLoggerTest.php, tests/Component/System/Git/GitCommandTest.php, tests/ProjectTestCase.php
=> Groom test code

composer.json
I'm using `php-coveralls` with `composer update --prefer-lowest` as part of my test matrix.
With 2.0.0 - 2.0.4, I get the error:
```
Error: Class 'Symfony\Component\Yaml\Parser' not found in /Users/gr4376/Projects/lib-gedcom/vendor/php-coveralls/php-coveralls/src/Bundle/CoverallsBundle/Config/Configurator.php on line 56
```
With 2.0.5, `php-coveralls` runs as expected.
=> Update minimum version of symfony/yaml to 2.0.5

composer.json, tests/Bundle/CoverallsBundle/Repository/JobsRepositoryTest.php
As it was described [here](https://github.com/php-coveralls/php-coveralls/issues/287), Coveralls can't be installed for the Laravel packages _(Guzzle 7 has been released a few days ago)_.
This PR adds Guzzle 7 support to fix that.
=> Add Guzzle 7 support

README.md, src/Bundle/CoverallsBundle/Collector/CiEnvVarsCollector.php, src/Bundle/CoverallsBundle/Entity/Exception/RequirementsNotSatisfiedException.php, src/Bundle/CoverallsBundle/Entity/JsonFile.php, tests/Bundle/CoverallsBundle/Api/JobsTest.php, tests/Bundle/CoverallsBundle/Collector/CiEnvVarsCollectorTest.php, tests/Bundle/CoverallsBundle/Command/CoverallsJobsCommandTest.php, tests/Bundle/CoverallsBundle/Console/ApplicationTest.php, tests/Bundle/CoverallsBundle/Entity/JsonFileTest.php
- Added the ability to send each build result as a parallel build by using environment variables. Following the practices in https://docs.coveralls.io/parallel-build-webhook
- Linked `TRAVIS_BUILD_NUMBER` to `CI_BUILD_NUMBER` so that the TravisCI Build number are passed in as the JSON parameters
=> Added COVERALLS_PARALLEL support and Configured CI_BUILD_NUMBER for Travis CI

.php_cs.dist, .travis.yml, composer.json, tests/Bundle/CoverallsBundle/Api/JobsTest.php, tests/Bundle/CoverallsBundle/Collector/CiEnvVarsCollectorTest.php, tests/Bundle/CoverallsBundle/Collector/CloverXmlCoverageCollectorTest.php, tests/Bundle/CoverallsBundle/Collector/GitInfoCollectorTest.php, tests/Bundle/CoverallsBundle/Command/CoverallsJobsCommandTest.php, tests/Bundle/CoverallsBundle/Config/ConfigurationTest.php, tests/Bundle/CoverallsBundle/Config/ConfiguratorTest.php, tests/Bundle/CoverallsBundle/Console/ApplicationTest.php, tests/Bundle/CoverallsBundle/Entity/Exception/RequirementsNotSatisfiedExceptionTest.php, tests/Bundle/CoverallsBundle/Entity/Git/CommitTest.php, tests/Bundle/CoverallsBundle/Entity/Git/GitTest.php, tests/Bundle/CoverallsBundle/Entity/Git/RemoteTest.php, tests/Bundle/CoverallsBundle/Entity/JsonFileTest.php, tests/Bundle/CoverallsBundle/Entity/MetricsTest.php, tests/Bundle/CoverallsBundle/Entity/SourceFileTest.php, tests/Bundle/CoverallsBundle/Repository/JobsRepositoryTest.php, tests/Component/File/PathTest.php, tests/Component/Log/ConsoleLoggerTest.php, tests/Component/System/Git/GitCommandTest.php, tests/ProjectTestCase.php
This PR
- Adds support for PHP 8 and PHPUnit 9.
- PHPUnit 8 should also work.
- It also contains [a shameless plug of an adapter package](https://github.com/sanmai/phpunit-legacy-adapter#phpunit-legacy-versions-adapter).
Replace #293
Fix #281
=> Add support for PHP 8 + PHPUnit 9

src/Bundle/CoverallsBundle/Collector/GitInfoCollector.php, tests/Bundle/CoverallsBundle/Collector/GitInfoCollectorTest.php
ref https://github.com/php-coveralls/php-coveralls/pull/275/files#r499891969
=> Fix support of branch name with hyphen and "(no branch)"

README.md
PHPUnit requires an environment variable to be set on Travis CI (`XDEBUG_MODE=coverage`). It's easy to overlook it if it's missing and can be frustrating to debug.
=> Update README with Travis CI configuration detail

composer.json
partial revert of #317
tests are failing when using psr/log@^3
=> Disallow `psr/log` v3

src/Bundle/CoverallsBundle/Config/Configurator.php
PHP 8.2 will deprecate two of the four currently supported syntaxes for embedding variables in double quoted text string/heredocs.
This libery contains three uses of embedded variables using braces after the dollar sign (`"${foo}"`), which is one of the deprecated forms.
This commit fixes all three.
Refs:
* https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation
=> PHP 8.2 | Fix deprecated embedded variables in text strings

tests/Bundle/CoverallsBundle/Api/JobsTest.php
Without a root directory, the `rtrim()` at the start of the `CloverXmlCoverageCollector::collect()` method will throw a `rtrim(): Passing null to parameter #1 ($string) of type string is deprecated` deprecation notice.
Setting the `Configuration::$rootDir` to an empty string bypasses this for these tests.
=> PHP 8.1 | Fix "passing null to non-nullable" deprecations (tests only)

tests/Bundle/CoverallsBundle/Entity/MetricsTest.php
This solves the following test failures (`master` is currently failing on a number of PHP versions):
```
1) PhpCoveralls\Tests\Bundle\CoverallsBundle\Entity\MetricsTest::shouldHaveLineCoverageOnConstructionWithCoverage
Failed asserting that 66.66666666666666 is identical to 66.66666666666667.
/home/runner/work/php-coveralls/php-coveralls/tests/Bundle/CoverallsBundle/Entity/MetricsTest.php:86
phpvfscomposer:///home/runner/work/php-coveralls/php-coveralls/vendor/phpunit/phpunit/phpunit:97
2) PhpCoveralls\Tests\Bundle\CoverallsBundle\Entity\MetricsTest::shouldMergeThatWithEmptyMetrics
Failed asserting that 66.66666666666666 is identical to 66.66666666666667.
/home/runner/work/php-coveralls/php-coveralls/tests/Bundle/CoverallsBundle/Entity/MetricsTest.php:102 …
```
=> MetricsTest: fix tests failing on imprecise floats

.github/workflows/ci.yml, box.json
Box 2 is no longer maintained and will not be made compatible with more recent PHP versions.
* Updated the Box configuration for changes made in Box 3 and 4.
* Explicitly set `check-requirements` to `false` as the requirements checker in Box 4 is not compatible with PHP < 7.2.
* Install the dependencies on the minimum supported PHP version.
* Updated the PHP setup to have the necessary PHP version, extensions and ini config needed to generate the PHAR with Box 4.
* Explicitly set the required Composer version to `2.2` as the autoload files generated with Composer 2.3+ are not compatible with PHP 5.5.
* Updated the PHAR generation command.
* Added validation and debug steps for the PHAR generation.
* Added a step to upload the Phar as a build artifact. The PHAR files uploaded in this way …
=> Upgrade PHAR generation to Box 4.x

README.md
- Since the CI changes into the GitHub action, it should replace the Travis CI with the GitHub action badge.
=> Replace Travis CI with the GitHub action badge

README.md
The build status badge in README was broken as it still pointed to Travis, while CI has been moved to GH Actions.
This commit fixes this by replacing the Travis badge with two badges for the GH Actions workflows.
And while GH Actions is already mentioned lower down in the README with a code example of how to use PHP Coveralls, it wasn't mentioned in the "Prerequisites" at the top of the README. Fixed now.
Before:
After:
=> README: fix broken badge and mention GH Actions

src/Bundle/CoverallsBundle/Repository/JobsRepository.php
The tests were failing on PHP 8.1 due to a `file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated` notice coming from the `JobsRepository::dumpJsonFile()` method.
While it would probably be unlikely for this error condition ever to be hit in a real life situation, it is something which is likely to happen in the tests and well, a little defensive coding goes a long way.
With this fix in place, the tests now pass on PHP 8.1 and PHP 8.2 and compatibility with both can be declared. :tada:
=> Fix PHP 8.1 compatibility

.github/workflows/ci.yml, src/Bundle/CoverallsBundle/Repository/JobsRepository.php
⚠️ This PR depends on PR #361 and can be marked "Ready for review" (and rebased) once PR #361 has been merged.
---
PR #361 should fix the remaining (known) PHP 8.1 error.
Once that PR has been merged, the CI runs against PHP 8.1, 8.2 and 8.3 should pass.
To that end, I'm adding builds against PHP 8.1, 8.2 and 8.3.
I'm also moving the code coverage recording from PHP 7.4 to PHP 8.2 to ensure high/low PHP is measured and adding an extra variant with `Xdebug` on high PHP too.
As PHP 8.3 is still in flux, builds against it are still allowed to fail.
=> GH Actions/CI: run the test suite against PHP 8.1, 8.2 and 8.3

README.md
It is a silly change, but it will make me a contributor and I will be able to work on https://github.com/php-coveralls/php-coveralls/pull/379 faster.
=> docs: remove duplicated word "other"
