README.md
Using the new require command you can make the install instructions a whole lot easier.
=> Updated composer install instructions

.travis.yml
Test the package on PHP 7, but allow failures.
=> Test on PHP 7

README.md
Reflects current state of CircleCI.  Also adjusted the xdebug.ini editing script so we don't need as many lines
=> Tweaked the CircleCI instructions

.travis.yml
Project claims to support PHP 5.3, so let test 5.3.3 with lowest deps versions ;)
=> Added 5.3.3 env to .travis.yml

composer.json
@tmatsuo could you merge it first?
no changes in versions
=> cleanup composer.json

src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configurator.php
=> Update YAML Parser call

composer.json
=> Allowing symfony/yaml 3.0.

src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Exception/RequirementsNotSatisfiedException.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Entity/Exception/RequirementsNotSatisfiedExceptionTest.php
=> Hide the REPO_TOKEN in the help message.

README.md
=> Added travis_retry to travis example.

src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Exception/RequirementsNotSatisfiedException.php
@keradus Sorry, please take a look
=> Use @var string[] instead of @var array.

README.md, src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configuration.php, src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configurator.php, src/Satooshi/Bundle/CoverallsV1Bundle/Config/CoverallsConfiguration.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Api/JobsTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Collector/CiEnvVarsCollectorTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/ConfigurationTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/ConfiguratorTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Repository/JobsRepositoryTest.php
We still need to keep it in CoverallsConfiguration for compatibility.
Fixes #126.
=> Remove srcDir from the Configuration.

bin/coveralls, box.json
=> Fixed the wrong path for calling from local git repo

README.md, build/config/phpmd.xml, src/Satooshi/Bundle/CoverallsV1Bundle/Command/CoverallsV1JobsCommand.php, src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configurator.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Command/CoverallsV1JobsCommandTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/ConfiguratorTest.php
=> Added --root_dir and --coverage_clover options to the command.

CHANGELOG.md, src/Satooshi/Bundle/CoverallsV1Bundle/Version.php
=> v0.7.0 release

phpunit.xml.dist, src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configurator.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/ConfiguratorTest.php, tests/prj/coveralls.yml
=> Deprecation notice when the config has src_dir.

src/Satooshi/Bundle/CoverallsV1Bundle/Config/Configurator.php, src/Satooshi/Bundle/CoverallsV1Bundle/Config/CoverallsConfiguration.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/ConfiguratorTest.php, tests/Satooshi/Bundle/CoverallsV1Bundle/Config/yaml/src_dir_not_found.yml
This change will go into the v0.8 release. Don't merge for v0.7 line.
=> Removed src_dir from CoverallsConfiguration.

.travis.yml
I'm doing this as a PR just because I want to see the travis builds pass.
=> Changed the travis config to upload the phar for all branches.

composer.json, src/Satooshi/Bundle/CoverallsV1Bundle/Version.php
The #157 is a breaking change and should be merged only into 2.0.x branch.
=> Start 2.0.0 development.

README.md
Also update installation instructions to make versioning clear.
Refs #166
=> Update README with new PHP requirements

README.md
=> Correct minimum version requirement for 1.x

src/Satooshi/Component/File/Path.php
=> Make relative path check Windows compatible

README.md, tests/Satooshi/Component/File/PathTest.php
=> PathTest - Fix tests on Windows

README.md, composer.json, devtools/composer.json
=> Use stable and semantic version constrains

phpunit.xml.dist, tests/PhpCoveralls/Bundle/CoverallsBundle/Collector/GitInfoCollectorTest.php, tests/PhpCoveralls/Bundle/CoverallsBundle/Config/ConfigurationTest.php, tests/PhpCoveralls/Bundle/CoverallsBundle/Entity/Exception/RequirementsNotSatisfiedExceptionTest.php, tests/PhpCoveralls/Bundle/CoverallsBundle/Entity/Git/CommitTest.php, tests/PhpCoveralls/Bundle/CoverallsBundle/Entity/Git/GitTest.php, tests/PhpCoveralls/Bundle/CoverallsBundle/Entity/Git/RemoteTest.php, tests/PhpCoveralls/Bundle/CoverallsBundle/Entity/MetricsTest.php, tests/PhpCoveralls/Component/Log/ConsoleLoggerTest.php, tests/PhpCoveralls/Component/System/Git/GitCommandTest.php, tests/PhpCoveralls/ProjectTestCase.php, tests/bootstrap.php
=> Enhancement: Use forward compatibility layer of phpunit/phpunit

src/Bundle/CoverallsBundle/Command/CoverallsJobsCommand.php, src/Bundle/CoverallsBundle/Repository/JobsRepository.php, tests/Bundle/CoverallsBundle/Repository/JobsRepositoryTest.php
=> Return non-0 status on command errors

src/Bundle/CoverallsBundle/Entity/Coveralls.php
=> JsonFile::__toString() - detect json_encode failure

README.md
this way it is not installed on production builds
=> Add --dev to install step

.travis.yml
Also `matrix` has been renamed to `jobs`.
=> Update .travis.yml to include PHP 7.4

src/Bundle/CoverallsBundle/Command/CoverallsJobsCommand.php, src/Bundle/CoverallsBundle/Config/Configurator.php
It will be useful when you want to store endpoint in environment variables on the CI server.
=> Allow to specify endpoint in arguments

src/Bundle/CoverallsBundle/Command/CoverallsJobsCommand.php, tests/Bundle/CoverallsBundle/Command/CoverallsJobsCommandTest.php
I think it will be nice to have the ability to send coverage reports to self-hosted service with self-signed certificates. For instance `goveralls` have such ability.
=> Add insecure option

src/Bundle/CoverallsBundle/Entity/Exception/RequirementsNotSatisfiedException.php
=> Correct spelling error in Github

src/Bundle/CoverallsBundle/Entity/Exception/RequirementsNotSatisfiedException.php
=> Fix #301 Add COVERALLS_REPO_TOKEN to error message

box.json
=> add file missing for PHP 8

src/Bundle/CoverallsBundle/Version.php
=> Update version in master to latest release

src/Bundle/CoverallsBundle/Entity/Coveralls.php, src/Bundle/CoverallsBundle/Entity/JsonFile.php
=> Added fallback to show where is problem with non-UTF8 chars.

src/Bundle/CoverallsBundle/Repository/JobsRepository.php, src/Component/Log/ConsoleLogger.php
=> Fix PHP 5.5 compatibility

src/Bundle/CoverallsBundle/Collector/CiEnvVarsCollector.php, src/Bundle/CoverallsBundle/Entity/Exception/RequirementsNotSatisfiedException.php, tests/Bundle/CoverallsBundle/Api/JobsTest.php, tests/Bundle/CoverallsBundle/Collector/CiEnvVarsCollectorTest.php
=> Changed `CIRCLE_BUILD_NUM` to `CIRCLE_WORKFLOW_ID`

.github/workflows/ci.yml
requires:
- https://github.com/php-coveralls/php-coveralls/pull/369
- Sf 7 released as stable
=> CI: explicit test under Symfony 7
